version: '3.1'

services:
  db:
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
    ports:
      - 5432:5432

  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db